# Generated by Django 5.2.6 on 2025-09-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('status', models.BooleanField()),
                ('rating', models.FloatField(null=True)),
                ('review', models.TextField(blank=True)),
            ],
        ),
    ]
