# Generated by Django 5.2.6 on 2025-09-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mybooks',
            old_name='book_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='mybooks',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
